name: xanhnow_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8

  # === Networking & Storage & JSON ===
  dio: ^5.3.0
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.9.0
  passkeys: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

  build_runner: ^2.4.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/ooxxi.png
    - assets/branding/app_icon.png
    - assets/branding/splash_logo.png
    - assets/illustrations/login_hero.svg

flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: assets/branding/app_icon.png
  image_path_android: assets/branding/app_icon.png
  remove_alpha_ios: true

flutter_native_splash:
  ios: true
  android: true
  color: "#ffffff"
  image: assets/branding/splash_logo.png
  android_12:
    color: "#ffffff"
    image: assets/branding/splash_logo.png
  web: false
